#!/bin/bash
PATH=$PATH:/Applications/CMake.app/Contents/bin
#mkdir mac32_build
#mkdir mac64_build
#cd mac32_build
#cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_OSX_ARCHITECTURES=i386 -DBUILD_GAME_QVM=0 -DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NATIVE_DLL=0 ..
#cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_OSX_ARCHITECTURES=i386 -DBUILD_GAME_QVM=0 -DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NATIVE_DLL=0 -DCMAKE_BUILD_TYPE=Debug ..
#make -j10
#cd ..
cd mac64_build
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DBUILD_GAME_QVM=0 -DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NATIVE_DLL=0 ..
make -j10
cd ..
rm -rf Unvanquished.app
./build-macosx-app-single.sh 64 mac64_build
zip -r9 mac Unvanquished.app
