#! /usr/bin/env bash

# ===========================================================================
#
# Copyright (c) 2022 Unvanquished Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ===========================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

cd '/Unvanquished/daemon/external_deps'

for target in ${targets}
do
	# For other architectures, the downloadable deps archive contains
	# everything required.
	case "${target}" in
	vm)
		# HACK: naclsdk is installed twice when building
		# both vm and linux-amd64-default.
		_exec ./build.sh 'linux-amd64-default' naclsdk install
		;;
	linux-*)
		# We now rebuild as much as libraries as possible so we get the
		# updated libraries on every platform and we get what we expect.
		# Also, some libraries may require us to rebuild them.
		# sdl3: Libraries are configured with unneeded dynamic dependencies.
		# curl: Static libraries are configured with unneeded protocols
		# that have extra dynamic dependencies.
		_exec ./build.sh "${target}-default" all install
		;;
	esac
done
