#! /usr/bin/env bash

# ===========================================================================
#
# Copyright (c) 2022 Unvanquished Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ===========================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

cd '/Unvanquished/daemon/external_deps'

for target in ${targets}
do
	case "${target}" in
	vm)
		# HACK: naclsdk is installed twice when building
		# both vm and linux-amd64-default.
		_exec ./build.sh 'linux-amd64-default' naclsdk naclports install
		;;
	linux-*)
		# Build some static libraries in the cases the package manager
		# didn't provide a satisfactory one.
		# openal, glew, ncurses: A static library is not provided.
		# sdl2: The static library is configured to have non-optional
		# dependencies on some dynamic libs.
		# curl: Static libraries are configured with unneeded protocols
		# that have extra dynamic dependencies.
		# ogg, opus, opusfile: We need to build them ourselve when building
		# both amd64 and arm64 at the same time because Debian buster's opus
		# static libs are not multiarch compatible.
		_exec ./build.sh "${target}-default" ogg opus opusfile curl sdl2 glew openal ncurses naclsdk install
		;;
	esac
done
