#! /usr/bin/env bash

# ===========================================================================
#
# Copyright (c) 2022 Unvanquished Developers
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ===========================================================================

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

if [ ! -f /darling-installed ]
then
	export DPREFIX=/darling-prefix

	echo 'y' | _exec darling shell xcode-select --install

	_exec darling shell touch /.dockerenv

	_exec curl -fsSL -o brew-install \
		'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh'

	# See https://docs.brew.sh/Installation
	export NONINTERACTIVE=1

	_exec darling shell ./brew-install

	_exec darling shell git \
		-C '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core' \
		checkout '103f18b14fbe28e2ff10a39cae19a79a54d636ab'

	# curl is already available
	_exec darling shell brew install p7zip cmake

	_exec touch /darling-installed
fi
