#! /usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

echo 'y' | _exec xcode-select --install

_exec touch /.dockerenv

_exec curl -fsSL -o brew-install \
	'https://raw.githubusercontent.com/Homebrew/install/a8c26acd449233fa2394930b440aac0c7047753c/install.sh'

# See https://docs.brew.sh/Installation
export NONINTERACTIVE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1

_exec ./brew-install

# brew-install switches it off automatically
export HOMEBREW_NO_INSTALL_FROM_API=1

_exec git \
	-C '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core' \
	checkout '103f18b14fbe28e2ff10a39cae19a79a54d636ab'

# curl is already available
_exec brew install p7zip cmake
